baseURL = 'https://acolavito.netlify.app/'
languageCode = 'en-us'
title = 'Home'
pluralizeListTitles = false
[taxonomies]
author = 'author'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  static = "static"
